git from setuptools import setup

setup(
    name='vpn',
    version='0.0.1',
    packages=['env.lib.python3.6.site-packages.PIL', 'env.lib.python3.6.site-packages.pip',
              'env.lib.python3.6.site-packages.pip.req', 'env.lib.python3.6.site-packages.pip.vcs',
              'env.lib.python3.6.site-packages.pip.utils', 'env.lib.python3.6.site-packages.pip.compat',
              'env.lib.python3.6.site-packages.pip.models', 'env.lib.python3.6.site-packages.pip._vendor',
              'env.lib.python3.6.site-packages.pip.commands', 'env.lib.python3.6.site-packages.pip.operations',
              'env.lib.python3.6.site-packages.dotenv', 'env.lib.python3.6.site-packages.urllib3',
              'env.lib.python3.6.site-packages.urllib3.util', 'env.lib.python3.6.site-packages.urllib3.contrib',
              'env.lib.python3.6.site-packages.urllib3.contrib._securetransport',
              'env.lib.python3.6.site-packages.urllib3.packages',
              'env.lib.python3.6.site-packages.urllib3.packages.backports',
              'env.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'env.lib.python3.6.site-packages.selenium', 'env.lib.python3.6.site-packages.selenium.common',
              'env.lib.python3.6.site-packages.selenium.webdriver',
              'env.lib.python3.6.site-packages.selenium.webdriver.ie',
              'env.lib.python3.6.site-packages.selenium.webdriver.edge',
              'env.lib.python3.6.site-packages.selenium.webdriver.opera',
              'env.lib.python3.6.site-packages.selenium.webdriver.chrome',
              'env.lib.python3.6.site-packages.selenium.webdriver.common',
              'env.lib.python3.6.site-packages.selenium.webdriver.common.html5',
              'env.lib.python3.6.site-packages.selenium.webdriver.common.actions',
              'env.lib.python3.6.site-packages.selenium.webdriver.remote',
              'env.lib.python3.6.site-packages.selenium.webdriver.safari',
              'env.lib.python3.6.site-packages.selenium.webdriver.android',
              'env.lib.python3.6.site-packages.selenium.webdriver.firefox',
              'env.lib.python3.6.site-packages.selenium.webdriver.support',
              'env.lib.python3.6.site-packages.selenium.webdriver.phantomjs',
              'env.lib.python3.6.site-packages.selenium.webdriver.webkitgtk',
              'env.lib.python3.6.site-packages.selenium.webdriver.blackberry',
              'env.lib.python3.6.site-packages.setuptools', 'env.lib.python3.6.site-packages.setuptools.extern',
              'env.lib.python3.6.site-packages.setuptools._vendor',
              'env.lib.python3.6.site-packages.setuptools._vendor.packaging',
              'env.lib.python3.6.site-packages.setuptools.command', 'env.lib.python3.6.site-packages.pytesseract',
              'env.lib.python3.6.site-packages.pkg_resources', 'env.lib.python3.6.site-packages.pkg_resources.extern',
              'env.lib.python3.6.site-packages.pkg_resources._vendor',
              'env.lib.python3.6.site-packages.pkg_resources._vendor.packaging',
              'env.lib64.python3.6.site-packages.PIL', 'env.lib64.python3.6.site-packages.pip',
              'env.lib64.python3.6.site-packages.pip.req', 'env.lib64.python3.6.site-packages.pip.vcs',
              'env.lib64.python3.6.site-packages.pip.utils', 'env.lib64.python3.6.site-packages.pip.compat',
              'env.lib64.python3.6.site-packages.pip.models', 'env.lib64.python3.6.site-packages.pip._vendor',
              'env.lib64.python3.6.site-packages.pip.commands', 'env.lib64.python3.6.site-packages.pip.operations',
              'env.lib64.python3.6.site-packages.dotenv', 'env.lib64.python3.6.site-packages.urllib3',
              'env.lib64.python3.6.site-packages.urllib3.util', 'env.lib64.python3.6.site-packages.urllib3.contrib',
              'env.lib64.python3.6.site-packages.urllib3.contrib._securetransport',
              'env.lib64.python3.6.site-packages.urllib3.packages',
              'env.lib64.python3.6.site-packages.urllib3.packages.backports',
              'env.lib64.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'env.lib64.python3.6.site-packages.selenium', 'env.lib64.python3.6.site-packages.selenium.common',
              'env.lib64.python3.6.site-packages.selenium.webdriver',
              'env.lib64.python3.6.site-packages.selenium.webdriver.ie',
              'env.lib64.python3.6.site-packages.selenium.webdriver.edge',
              'env.lib64.python3.6.site-packages.selenium.webdriver.opera',
              'env.lib64.python3.6.site-packages.selenium.webdriver.chrome',
              'env.lib64.python3.6.site-packages.selenium.webdriver.common',
              'env.lib64.python3.6.site-packages.selenium.webdriver.common.html5',
              'env.lib64.python3.6.site-packages.selenium.webdriver.common.actions',
              'env.lib64.python3.6.site-packages.selenium.webdriver.remote',
              'env.lib64.python3.6.site-packages.selenium.webdriver.safari',
              'env.lib64.python3.6.site-packages.selenium.webdriver.android',
              'env.lib64.python3.6.site-packages.selenium.webdriver.firefox',
              'env.lib64.python3.6.site-packages.selenium.webdriver.support',
              'env.lib64.python3.6.site-packages.selenium.webdriver.phantomjs',
              'env.lib64.python3.6.site-packages.selenium.webdriver.webkitgtk',
              'env.lib64.python3.6.site-packages.selenium.webdriver.blackberry',
              'env.lib64.python3.6.site-packages.setuptools', 'env.lib64.python3.6.site-packages.setuptools.extern',
              'env.lib64.python3.6.site-packages.setuptools._vendor',
              'env.lib64.python3.6.site-packages.setuptools._vendor.packaging',
              'env.lib64.python3.6.site-packages.setuptools.command', 'env.lib64.python3.6.site-packages.pytesseract',
              'env.lib64.python3.6.site-packages.pkg_resources',
              'env.lib64.python3.6.site-packages.pkg_resources.extern',
              'env.lib64.python3.6.site-packages.pkg_resources._vendor',
              'env.lib64.python3.6.site-packages.pkg_resources._vendor.packaging'],
    url='https://ya.ru',
    license='my_license',
    author='Denis',
    author_email='e@mail.com',
    description='my_description'
)
